language: node_js
node_js:
  - "10"
services:
  - docker
branches:
  only:
    - master

before_install:
  - npm install

script:
  - npm test
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t pea3nut/pxer-homepage2:latest .
  - docker push pea3nut/pxer-homepage2:latest
